[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm ci",
  "cd alh-ui && npm ci"
]

[phases.build]
cmds = [
  "cd alh-ui && npm run build",
  "rm -rf dist",
  "cp -r alh-ui/dist dist"
]

[start]
cmd = "node src/server.js"
